name: spotify

packages:
  - ./data
  - ./domain
  - ./pos
  - ./initializer
flutter: true

command:
  bootstrap:
    runPubGetInParallel: false
  clean:
    hooks:
      post: melos exec --flutter --concurrency=3 -- "flutter clean"

scripts:
  # build runner build
  build_all:
    run: dart pub global run melos exec --depends-on="build_runner" "dart run build_runner build --delete-conflicting-outputs"
    description: build_runner build all modules.

  build_data:
    run: dart pub global run melos exec --fail-fast --scope="*data*" --depends-on="build_runner" "dart run build_runner build --delete-conflicting-outputs"
    description: build_runner build data module.

  build_domain:
    run: dart pub global run melos exec --fail-fast --scope="*domain*" --depends-on="build_runner" "dart run build_runner build --delete-conflicting-outputs"
    description: build_runner build domain module.

  build_pos:
    run: dart pub global run melos exec --fail-fast --scope="*pos*" --depends-on="build_runner" "dart run build_runner build --delete-conflicting-outputs"
    description: build_runner build pos module.
