name: domain
description: "Spotify - Domain"
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  freezed_annotation: ^2.4.1

  # Dependency Injection
  get_it: ^8.0.3
  injectable: ^2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # Code generation
  build_runner: ^2.4.0
  freezed: ^2.5.2 #
  injectable_generator: ^2.6.1 #
